version: '3'
services:
 alpine-gitops:
  tty: true
  stdin_open: true
  image: alpine
  environment:
   - pop=book
   - hoopl=u
  volumes:
   - ./html/${PORTAINER_EDGE_GROUP}.html:/home/config-edgegroup.txt
   - ./html/${PORTAINER_EDGE_ID}.html:/home/config-edgeid.txt
