version: '3'  # To use this make sure that you have an edge group that has the name gitops

services:
  alpine-gitops:
    image: alpine:latest
    tty: true
    stdin_open: true
    deploy:
      placement:
        constraints:
          - node.role == manager
    environment:
      - ${ENV:-test}=full-life
    volumes:
      - ./html/${PORTAINER_EDGE_GROUP}:/home/config-edgegroup
