version: '3'
services:
 alpine-gitops:
  tty: true
  stdin_open: true
  image: alpine
  environment:
   - hello=hi
   - make=change
  volumes:
   - ./html/${PORTAINER_EDGE_ID}.html:/home/config-edgeid
