version: '3' #To use this make sure that you have an edge group that has the name gitops
services:
 alpine-gitops:
  image: alpine
  tty: true
  stdin_open: true
  environment:
   - hello={{value}}
   - hoopla={{value2}}
  volumes:
   - ./html/${PORTAINER_EDGE_GROUP}.html:/config-edgegroup
